### ISSUE TITLE
Merging bug fixes for def.format.reaeration

### ISSUE THREAD

**Issue by michelleckelly** [NEONScience/NEON-reaeration#9]
Currently, def.format.reaeration returns a dataframe with NA in the eventID column. I made the following two changes, which seemed to fix the problem and make the eventID column populate correctly:

Comment out Line 81: There is now a siteID column in dsc_fieldDataADCP, so this line can be commented out. Otherwise, the siteID column in dsc_fieldDataADCP gets overwritten with NAs, as the stationID column no longer exists.

Line 125: Add 'eventID' to the by = c(...) list, otherwise when rea_backgroundFieldCondData and rea_fieldData merge, columns eventID.x and eventID.y will be created, which won't be preserved in the output dataframe.

I think it's likely that line 120 might have to be changed in the same way, but I haven't pulled any data for a site with rea_backgroundFieldSaltData yet, and so haven't tested that.

For reference:
Site: BLDE
Date start: 2018-01
Date end: 2018-12
Platform: macOS Catalina v10.15.7
R version: 3.6.1

**Comment by kcawley** [comment]
@michelleckelly  Thanks for these updates! I will take a detailed look in the next couple of days and make updates to fix this!

**Comment by kcawley** [comment]
@michelleckelly  Took a little longer than I had hoped, but along with a bunch of other changes, I pushed a fix today. Please install version 0.9.3 for the changes.
